import { OUTCOMES, AWARDS, readPanel, readResults, problemsWithResults, certificateNumber, entriesOpen } from './domain/grading.mjs';
let pass = 0, fail = 0;
const ok = (n, c, d = '') => c ? (pass++, console.log(`  ✓ ${n}`)) : (fail++, console.log(`  ✗ ${n}  ${d}`));
const today = '2026-10-02';
const e = (id, name, status = 'entered') => ({ entry_id: id, name, status });
console.log('\nPANEL AND RESULTS');
ok('panel numbers are upper-cased and deduplicated', JSON.stringify(readPanel('m-1, M-1 m-2;m-3')) === '["M-1","M-2","M-3"]');
ok('results come from per-row fields', JSON.stringify(readResults({ result_a: 'pass', note_a: ' good  kata ', result_b: '' }, ['a', 'b'])) === '{"a":{"outcome":"pass","notes":"good kata"}}');
const entries = [e('a', 'Ann'), e('b', 'Bob'), e('c', 'Cat', 'withdrawn')];
const good = { a: { outcome: 'pass' }, b: { outcome: 'fail' } };
ok('a complete night is fine', problemsWithResults({ entries, results: good, panel: ['M-1'], date: today }, today).length === 0);
ok('a withdrawn entrant needs no result', !problemsWithResults({ entries, results: good, panel: ['M-1'], date: today }, today).join().includes('Cat'));
ok('everybody needs an outcome', problemsWithResults({ entries, results: { a: { outcome: 'pass' } }, panel: ['M-1'], date: today }, today).some((p) => /Bob/.test(p)));
ok('a pass needs a panel', problemsWithResults({ entries, results: good, panel: [], date: today }, today).some((p) => /panel/.test(p)));
ok('all fails need no panel', problemsWithResults({ entries, results: { a: { outcome: 'fail' }, b: { outcome: 'absent' } }, panel: [], date: today }, today).length === 0);
ok('not in the future', problemsWithResults({ entries, results: good, panel: ['M-1'], date: '2026-12-01' }, today).some((p) => /before it has happened/.test(p)));
ok('a real date', problemsWithResults({ entries, results: good, panel: ['M-1'], date: '2026-02-30' }, today).some((p) => /date/.test(p)));
ok('nobody entered', problemsWithResults({ entries: [], results: {}, panel: [], date: today }, today).includes('Nobody is entered.'));
ok('only passes are awarded', AWARDS.has('pass') && AWARDS.has('provisional') && !AWARDS.has('fail') && !AWARDS.has('absent') && Object.keys(OUTCOMES).length === 4);
console.log('\nCERTIFICATES');
ok('numbered', certificateNumber('moknz', 2026, 7) === 'MOKNZ-G-2026-0007');
ok('a missing prefix still gives a number', certificateNumber('', 2026, 1) === 'G-G-2026-0001');
console.log('\nENTRIES');
const ev = { status: 'published', entries_open: null, entries_close: null, finalised_on: null };
ok('open', entriesOpen(ev, '2026-10-02T00:00:00Z').open);
ok('a draft is not open', !entriesOpen({ ...ev, status: 'draft' }, 'x').open);
ok('closed', !entriesOpen({ ...ev, entries_close: '2026-09-01T00:00:00Z' }, '2026-10-02T00:00:00Z').open);
ok('not yet', !entriesOpen({ ...ev, entries_open: '2026-11-01T00:00:00Z' }, '2026-10-02T00:00:00Z').open);
ok('finished', !entriesOpen({ ...ev, finalised_on: '2026-09-30' }, '2026-10-02T00:00:00Z').open);
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
