import * as E from './domain/enquiry.mjs';
let pass = 0, fail = 0;
const ok = (n, c) => c ? (pass++, console.log(`  ✓ ${n}`)) : (fail++, console.log(`  ✗ ${n}`));
console.log('\nREADING');
const r = E.readEnquiry({ name: '  Sam   Walker ', email: ' SAM@X.NZ ', message: 'Hi\r\nthere\u0000', kind: 'trial', who: 'my son,   9' });
ok('tidied', r.name === 'Sam Walker' && r.email === 'sam@x.nz' && r.message === 'Hi\nthere' && r.who === 'my son, 9');
ok('anything but trial is contact', E.readEnquiry({ kind: '<x>' }).kind === 'contact');
ok('lengths are capped', E.readEnquiry({ message: 'a'.repeat(5000) }).message.length === 2000 && E.readEnquiry({ name: 'a'.repeat(500) }).name.length === 100);
console.log('\nWHAT IS NEEDED');
const good = { kind: 'contact', name: 'Sam', email: 'sam@x.nz', phone: '', who: '', message: 'Hello' };
ok('a good one is fine', E.problemsWithEnquiry(good).length === 0);
ok('a name', E.problemsWithEnquiry({ ...good, name: '' }).length === 1);
ok('a real-looking email', ['sam@', 'sam@x', 'a b@x.nz', 'a@x.nz,b@y.nz', '"a"@x.nz', 'x@y.nz\nBcc:z@z.nz'].every((email) => E.problemsWithEnquiry({ ...good, email }).length >= 1));
ok('a contact needs a message; a trial does not', E.problemsWithEnquiry({ ...good, message: '' }).length === 1 && E.problemsWithEnquiry({ ...good, kind: 'trial', message: '' }).length === 0);
ok('a pile of links is refused, one or two is fine', E.problemsWithEnquiry({ ...good, message: 'http://a.com http://b.com http://c.com' }).length === 1 && E.problemsWithEnquiry({ ...good, message: 'see http://a.com' }).length === 0);
console.log('\nROBOTS AND ORIGINS');
ok('the hidden box catches robots', E.looksLikeRobot({ website: 'http://spam' }) && !E.looksLikeRobot({ website: '' }) && !E.looksLikeRobot({}));
ok('same site passes', E.sameSite({ host: 'a.nz', origin: 'https://a.nz' }) && E.sameSite({ host: 'a.nz', referer: 'https://a.nz/contact' }) && E.sameSite({ host: 'a.nz' }));
ok('another site is refused', !E.sameSite({ host: 'a.nz', origin: 'https://evil.example' }) && !E.sameSite({ host: 'a.nz', origin: 'not a url' }));
console.log('\nTHE EMAIL');
const b = E.emailBody({ ...good, kind: 'trial', who: 'my son, 9', phone: '021' }, 'Whanganui');
ok('says who, how to reach them, and for whom', /Whanganui/.test(b) && /sam@x.nz/.test(b) && /my son, 9/.test(b) && /021/.test(b));
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
