import { cell, toCsv, cents, readRange, fileName } from './domain/csv.mjs';
let pass = 0, fail = 0;
const ok = (n, c, d = '') => c ? (pass++, console.log(`  ✓ ${n}`)) : (fail++, console.log(`  ✗ ${n}  ${d}`));
console.log('\nCELLS');
ok('plain text', cell('Sam') === 'Sam');
ok('null is empty', cell(null) === '' && cell(undefined) === '');
ok('commas are quoted', cell('Walker, Sam') === '"Walker, Sam"');
ok('quotes are doubled', cell('say "hi"') === '"say ""hi"""');
ok('newlines are quoted', cell('a\nb') === '"a\nb"');
ok('a formula is defused', cell('=HYPERLINK("x")') === `"'=HYPERLINK(""x"")"`, cell('=HYPERLINK("x")'));
ok('+ - @ are defused', cell('+1').startsWith("'") && cell('@SUM(A1)').startsWith("'") && cell('-cmd|x').startsWith("'"));
ok('a negative number stays a number', cell('-12.50') === '-12.50' && cell(-5) === '-5');
ok('a phone with a plus is defused', cell('+64 21 555') === "'+64 21 555");
ok('a date is a date', cell(new Date('2026-10-02T00:00:00Z')) === '2026-10-02');
console.log('\nFILES');
const out = toCsv([{ key: 'a', label: 'Name' }, { key: 'b', label: 'Fee' }], [{ a: 'Whānganui', b: 5 }, { a: 'Two, three', b: null }]);
ok('begins with a byte order mark', out.charCodeAt(0) === 0xfeff);
ok('rows end CRLF', out.endsWith('\r\n') && out.split('\r\n').length === 4);
ok('header and rows', out.includes('Name,Fee') && out.includes('"Two, three",'));
ok('no rows still has a header', toCsv([{ key: 'a', label: 'A' }], []) === '﻿A\r\n');
ok('cents', cents(12345) === '123.45' && cents(null) === '');
console.log('\nRANGES');
ok('defaults to the last year', readRange(undefined, undefined, '2026-10-02').from === '2025-10-02');
ok('keeps good dates', JSON.stringify(readRange('2026-01-01', '2026-02-01', '2026-10-02')) === '{"from":"2026-01-01","to":"2026-02-01"}');
ok('swaps backwards dates', readRange('2026-03-01', '2026-01-01', '2026-10-02').from === '2026-01-01');
ok('ignores rubbish', readRange('x', "';drop", '2026-10-02').to === '2026-10-02');
ok('safe file names', fileName('wh/anganui', 'fees', '2026-10-02') === 'wh_anganui-fees-2026-10-02.csv');
console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
